/* Generated By:JJTree: Do not edit this line. ASTIntervalExp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pilots.compiler.parser;

public
class ASTIntervalExp extends SimpleNode {
  public ASTIntervalExp(int id) {
    super(id);
  }

  public ASTIntervalExp(PilotsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PilotsParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f24e282cd2bf9baed84d130de6d3edf5 (do not edit this line) */
