/* Generated By:JJTree&JavaCC: Do not edit this line. PilotsParserConstants.java */
package pilots.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PilotsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM_START = 10;
  /** RegularExpression Id. */
  int INPUTS = 11;
  /** RegularExpression Id. */
  int CONSTANTS = 12;
  /** RegularExpression Id. */
  int OUTPUTS = 13;
  /** RegularExpression Id. */
  int ERRORS = 14;
  /** RegularExpression Id. */
  int SIGNATURES = 15;
  /** RegularExpression Id. */
  int MODES = 16;
  /** RegularExpression Id. */
  int CORRECTS = 17;
  /** RegularExpression Id. */
  int USING = 18;
  /** RegularExpression Id. */
  int AT = 19;
  /** RegularExpression Id. */
  int EVERY = 20;
  /** RegularExpression Id. */
  int CLOSEST = 21;
  /** RegularExpression Id. */
  int EUCLIDEAN = 22;
  /** RegularExpression Id. */
  int INTERPOLATE = 23;
  /** RegularExpression Id. */
  int MODEL = 24;
  /** RegularExpression Id. */
  int ESTIMATE = 25;
  /** RegularExpression Id. */
  int WHEN = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int NSEC = 28;
  /** RegularExpression Id. */
  int USEC = 29;
  /** RegularExpression Id. */
  int MSEC = 30;
  /** RegularExpression Id. */
  int SEC = 31;
  /** RegularExpression Id. */
  int MIN = 32;
  /** RegularExpression Id. */
  int HOUR = 33;
  /** RegularExpression Id. */
  int DAY = 34;
  /** RegularExpression Id. */
  int SQRT = 35;
  /** RegularExpression Id. */
  int SIN = 36;
  /** RegularExpression Id. */
  int COS = 37;
  /** RegularExpression Id. */
  int TAN = 38;
  /** RegularExpression Id. */
  int ARCSIN = 39;
  /** RegularExpression Id. */
  int ARCCOS = 40;
  /** RegularExpression Id. */
  int ARCTAN = 41;
  /** RegularExpression Id. */
  int ABS = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int OR = 44;
  /** RegularExpression Id. */
  int XOR = 45;
  /** RegularExpression Id. */
  int NOT = 46;
  /** RegularExpression Id. */
  int IN = 47;
  /** RegularExpression Id. */
  int PROGRAM_END = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;
  /** RegularExpression Id. */
  int LPAR = 50;
  /** RegularExpression Id. */
  int RPAR = 51;
  /** RegularExpression Id. */
  int LBRAC = 52;
  /** RegularExpression Id. */
  int RBRAC = 53;
  /** RegularExpression Id. */
  int COMMA = 54;
  /** RegularExpression Id. */
  int DOTS = 55;
  /** RegularExpression Id. */
  int INTEGER = 56;
  /** RegularExpression Id. */
  int SCALEFACTOR = 57;
  /** RegularExpression Id. */
  int REAL = 58;
  /** RegularExpression Id. */
  int LETTER = 59;
  /** RegularExpression Id. */
  int VAR = 60;
  /** RegularExpression Id. */
  int STRING = 61;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "\"program\"",
    "\"inputs\"",
    "\"constants\"",
    "\"outputs\"",
    "\"errors\"",
    "\"signatures\"",
    "\"modes\"",
    "\"correct\"",
    "\"using\"",
    "\"at\"",
    "\"every\"",
    "\"closest\"",
    "\"euclidean\"",
    "\"interpolate\"",
    "\"model\"",
    "\"estimate\"",
    "\"when\"",
    "\"times\"",
    "\"nsec\"",
    "\"usec\"",
    "\"msec\"",
    "\"sec\"",
    "\"min\"",
    "\"hour\"",
    "\"day\"",
    "\"sqrt\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"abs\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"not\"",
    "\"in\"",
    "\"end\"",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"..\"",
    "<INTEGER>",
    "<SCALEFACTOR>",
    "<REAL>",
    "<LETTER>",
    "<VAR>",
    "<STRING>",
    "\";\"",
    "\"=\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"==\"",
  };

}
