/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 7.0.9 */
package pilots.compiler.parser;

public interface PilotsParserTreeConstants
{
  public int JJTPILOTS = 0;
  public int JJTINPUT = 1;
  public int JJTCONSTANT = 2;
  public int JJTOUTPUT = 3;
  public int JJTERROR = 4;
  public int JJTSIGNATURE = 5;
  public int JJTMODE = 6;
  public int JJTESTIMATE = 7;
  public int JJTCORRECT = 8;
  public int JJTVARS = 9;
  public int JJTCONSTINSIGNATURE = 10;
  public int JJTDIM = 11;
  public int JJTMETHOD = 12;
  public int JJTMETHODS = 13;
  public int JJTTIME = 14;
  public int JJTEXPS = 15;
  public int JJTEXP = 16;
  public int JJTEXP2 = 17;
  public int JJTINTERVALEXP = 18;
  public int JJTFUNC = 19;
  public int JJTNUMBER = 20;
  public int JJTVALUE = 21;


  public String[] jjtNodeName = {
    "Pilots",
    "Input",
    "Constant",
    "Output",
    "Error",
    "Signature",
    "Mode",
    "Estimate",
    "Correct",
    "Vars",
    "ConstInSignature",
    "Dim",
    "Method",
    "Methods",
    "Time",
    "Exps",
    "Exp",
    "Exp2",
    "IntervalExp",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=1b40bccd304b3d873fc31235d5fbbf06 (do not edit this line) */
